name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest Meson
      run: pip3 install --user meson
    - name: Install transpiler dependencies
      run: pip3 install --user jinja2
    - name: Run tests with ASan
      run: |
        meson setup builddir_asan -Db_sanitize=address
        ninja -C builddir_asan test
    - name: Run tests with LSan
      run: |
        meson setup builddir_lsan -Db_sanitize=leak
        ninja -C builddir_lsan test

  macos-tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare virtual env
      run: |
        python3 -m venv pvenv
        source pvenv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
        echo VIRTUAL_ENV=$VIRTUAL_ENV >> $GITHUB_ENV
    - name: Install latest Meson
      run: pip3 install meson
    - name: Install transpiler dependencies
      run: pip3 install jinja2
    - name: Run tests with ASan
      run: |
        meson setup builddir_asan -Db_sanitize=address
        ninja -C builddir_asan test
    - name: Run tests with LSan
      run: |
        meson setup builddir_lsan -Db_sanitize=leak -Db_lundef=false
        ninja -C builddir_lsan test
