name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest Meson
      run: pip3 install --user meson
    - name: Install transpiler dependencies
      run: pip3 install --user jinja2
    - name: Configure build
      run: meson setup builddir
    - name: Run tests
      run: ninja -C builddir test

  macos-tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install latest Meson
      run: pip3 install --user meson
    - name: Install transpiler dependencies
      run: pip3 install --user jinja2
    - name: Configure build
      run: meson setup builddir
    - name: Run tests
      run: ninja -C builddir test
